export const JOB_FILE = 'JOB_FILE';
export const JOB_SETTINGS = 'JOB_SETTINGS';
export const USE_SETTINGS_FLAG = 'USE_SETTINGS_FLAG';

export const JOB_STATUS = {
    CREATED: 'CREATED',
    PROCESSING: 'PROCESSING',
    FINISHED: 'FINISHED',
    ERROR: 'ERROR',
    NOT_FOUND: 'NOT_FOUND',
};

export const TASK_STATUS = {
    CREATED: 'CREATED',
    QUEUED: 'QUEUED',
    PROCESSING: 'PROCESSING',
    FINISHED: 'FINISHED',
    ERROR: 'ERROR',
};
